### ISSUE TITLE
Compressed trace files

### ISSUE THREAD

**Issue by cgaebel** [janestreet/magic-trace#154]
Trace files are big and compress really well, 5x-ish in my experience. Could magic-trace write out compressed traces instead of raw traces?

Perfetto already has support for loading gzipped traces. But gzip is really slow (fingers crossed for Sapphire Rapids, but that's years from being commonplace).

As far as I can tell, we have two options here:

- teach magic-trace to write gzipped traces, or
- teach magic-trace to write `zstd`'d traces, and also teach perfetto to load them.

The first option is easier, but the second option would be faster to save and load. FWIW, Tudor thinks zstd is overkill because we're so slow at decoding otherwise.

- [Perfetto's gzip_trace_parser.cc](https://github.com/janestreet/perfetto/blob/jane-public-patches/src/trace_processor/importers/gzip/gzip_trace_parser.cc)
- [zstd ocaml bindings](https://ocaml.janestreet.com/ocaml-core/v0.12/doc/zstandard/Zstandard/index.html)
- [gzip ocaml bindings](https://github.com/hcarty/ezgzip)
- [libdeflate](https://github.com/ebiggers/libdeflate) has the tall claim of gzipping faster that zstd

**Comment by hlian** [comment]
@Lilydemi has a PR for this!
