### ISSUE TITLE
Binaries with DWARF5 debug info fail at decoding time

### ISSUE THREAD

**Issue by StephanDollberg** [janestreet/magic-trace#2]
It seems that magic-trace struggles with DWARF5 which gcc11 now uses by default. Testing a simple program compiled with DWARF5 info gives:

```
[Attaching to 4199088]
[Snapshot taken!]
...
[ perf record: Woken up 2 times to write data ]
[Finished recording!]
[ perf record: Captured and wrote 4.012 MB /tmp/magic_trace.tmp.848576/perf.data ]
[Decoding, this may take 30s or so...]
(monitor.ml.Error
 ("Owee_buf.Invalid_format(\"unknown .debug_line version\")")
 ("Raised at Owee_buf.invalid_format in file \"src/owee_buf.ml\", line 22, characters 25-51"
  "Called from Owee_buf.assert_format in file \"src/owee_buf.ml\" (inlined), line 26, characters 4-22"
  "Called from Owee_debug_line.read_header in file \"src/owee_debug_line.ml\", line 54, characters 2-80"
  "Called from Owee_debug_line.read_chunk in file \"src/owee_debug_line.ml\", line 82, characters 12-27"
  "Called from Magic_trace_core__Elf.addr_table.(fun).load_table_next in file \"core/elf.ml\", line 103, characters 12-45"
  "Called from Base__Option.iter in file \"src/option.ml\" (inlined), line 68, characters 14-17"
  "Called from Magic_trace_core__Elf.addr_table in file \"core/elf.ml\", line 90, characters 2-1023"
  "Called from Magic_trace_lib__Trace.Make_commands.decode_to_trace.(fun) in file \"src/trace.ml\", line 70, characters 25-43"
  "Called from Tracing__Tool_output.write_and_view in file \"src/tool_output.ml\", line 32, characters 16-19"
  "Called from Async_kernel__Deferred0.bind.(fun) in file \"src/deferred0.ml\", line 54, characters 64-69"
  "Called from Async_kernel__Job_queue.run_jobs in file \"src/job_queue.ml\", line 167, characters 6-47"
  "Caught by monitor Monitor.protect"))
```

Passing `-gdwarf-4` to gcc makes the issue go away.

**Comment by poechsel** [comment]
Thanks for the bug report!
This is a limitation of Owee, the library we're using to decode dwarf information. 
We've got no plans to support `-dwarf-5` in the near future so for now you'll have to continue passing `-gdwarf-4` to gcc.

**Comment by gretay-js** [comment]
I think that debug info is optional and nice when viewing the traces, but it should be easy to detect the mismatch and skip, with a warning, so that magic trace can be used without rebuilding the tracee with special options.

**Comment by cgaebel** [comment]
We need to support dwarf-v5 soon if gcc and clang are producing it by default. I don't have a great story for how we're going to do that just yet, but we'll come up with something.

**Comment by cgaebel** [comment]
[let-def/owee#14](https://github.com/let-def/owee/issues/14) is why this doesn't work today. Still unsure if fixing owee or switching to something with dwarf 5 support is the right way forward.

**Comment by cgaebel** [comment]
I've made some forward progress on this, it should be fixed soon. see https://github.com/let-def/owee/pull/18 for more details.
