### ISSUE TITLE
Add a mode to automatically capture a trace and exit

### ISSUE THREAD

**Issue by knrafto** [janestreet/magic-trace#258]
We have a script to automatically run magic-trace during tests. Right now we have to start magic-trace, wait for some amount of time, and then send SIGINT to magic-trace using pkill. Unfortunately, the time we need to wait is not predictable (it could be 5s or more for large binaries) so this occasionally sends SIGINT too early. If would be nice if we could tell magic-trace to take a snapshot and exit when it's done.

I tried to implement this myself but I couldn't find a good way to know when perf is "ready". It looks like magic-trace itself has a hardcoded [500ms](https://github.com/janestreet/magic-trace/blob/4da617e39e101ad746b9a0dcd9e36ac62d50d70b/src/perf_tool_backend.ml#L401) timeout, which is definitely not long enough for our binaries. Do you have any ideas?

**Comment by knrafto** [comment]
(sorry, this is a feature request, not a bug report, but I don't see how to change the labels now)

**Comment by Xyene** [comment]
I think https://github.com/janestreet/magic-trace/issues/230 should address this. You could write `magic-trace attach -p [your process' pid] -- true` and that would do the right thing.

**Comment by knrafto** [comment]
Interesting, thanks! Closing to dedup
