### ISSUE TITLE
Failed to start with error `unable to interpret perf version string`

### ISSUE THREAD

**Issue by theidexisted** [janestreet/magic-trace#273]
Thanks for helping us make magic-trace better!

Please consider answering any subset of the following questions, based on what you think
is most relevant to your report:

- What happened?
Failed to start with error `unable to interpret perf version string`, full output:
```
(monitor.ml.Error
 ("unable to interpret perf version string"
  (version_string "perf version \n"))
 ("Raised at Base__Error.raise in file \"src/error.ml\" (inlined), line 9, characters 14-30"
  "Called from Base__Error.raise_s in file \"src/error.ml\", line 10, characters 19-40"
  "Called from Magic_trace_lib__Perf_capabilities.detect_exn.(fun) in file \"src/perf_capabilities.ml\", line 73, characters 16-65"
  "Called from Async_kernel__Deferred1.M.map.(fun) in file \"src/deferred1.ml\", line 17, characters 40-45"
  "Called from Async_kernel__Job_queue.run_jobs in file \"src/job_queue.ml\", line 167, characters 6-47"
  "Caught by monitor Monitor.protect"))
```
- What did you expect to happen?
Run smoothly.
- How can we, magic-trace developers, reproduce the issue you're seeing?
Seems caused by the perf version string parsing, maybe it's a bug in the apt package?
- What version of perf userspace tools are you running? `perf --version`
Actually installed `linux-tools-5.19.0-35-generic`, `5.19.0-35-generic #36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`
Output for `perf --version`:
```
->perf --version
perf version
```
- What CPU do you have? `cat /proc/cpuinfo`
```
processor       : 15
vendor_id       : GenuineIntel
cpu family      : 6
model           : 141
model name      : 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
stepping        : 1
microcode       : 0x42
cpu MHz         : 2300.000
cache size      : 24576 KB
physical id     : 0
siblings        : 16
core id         : 7
cpu cores       : 8
apicid          : 15
initial apicid  : 15
fpu             : yes
fpu_exception   : yes
cpuid level     : 27
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l2 invpcid_single cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves split_lock_detect dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid movdiri movdir64b fsrm avx512_vp2intersect md_clear ibt flush_l1d arch_capabilities
vmx flags       : vnmi preemption_timer posted_intr invvpid ept_x_only ept_ad ept_1gb flexpriority apicv tsc_offset vtpr mtf vapic ept vpid unrestricted_guest vapic_reg vid ple pml ept_mode_based_exec tsc_scaling
bugs            : spectre_v1 spectre_v2 spec_store_bypass swapgs eibrs_pbrsb
bogomips        : 4608.00
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:
```
- If you're reporting a UI bug, can you provide the trace file and/or screenshots
  of the probem?

        
Please also consider scanning the [existing set of issues](https://github.com/janestreet/magic-trace/issues)
for other people reporting the same thing, and checking out the
[FAQ](https://github.com/janestreet/magic-trace/wiki/FAQ) just in case you're running into
a common pitfall.

**Comment by Xyene** [comment]
Thanks for reporting this. It does look like something is borked with your perf package, and it's not obvious what magic-trace could reasonably do here. We need to know what version of perf we're running with, in order to work around certain perf bugs, and conditionally enable some features.

On the perf side, it looks like something went wrong during compilation, somewhere upstream of https://github.com/torvalds/linux/blob/da8e7da11e4ba758caf4c149cc8d8cd555aefe5f/tools/perf/util/PERF-VERSION-GEN#L43.

I would recommend reporting this upstream. I believe the right place to do so is https://launchpad.net/ubuntu/+source/linux/+bugs.

You can also try installing a different version of perf.
