### ISSUE TITLE
Implement a `perf script --dlfilter` backend

### ISSUE THREAD

**Issue by Xyene** [janestreet/magic-trace#32]
Currently, we spend a lot of time `sscan`-ing textual output from `perf script`, and filter out branches within the same symbol in OCaml.

On recent (5.14+) `perf` installs, we could offload this to `perf script --dlfilter`, and have a short native object that does the filtering for us. Ref https://man7.org/linux/man-pages/man1/perf-dlfilter.1.html.

**Comment by cgaebel** [comment]
When we do this, we should make sure to maintain support for pre-5.14 perf. Older perfs are extremely common, and most people aren't willing to install a recent perf userspace to use with their older kernel.
