### ISSUE TITLE
Support increasing the snapshot buffer size

### ISSUE THREAD

**Issue by Xyene** [janestreet/magic-trace#33]
The snapshot buffer can be ~arbitrarily sized, and is passed as the argument to `--snapshot` in `perf`. Larger buffers would allow for more data to be captured and displayed.

Ref https://man7.org/linux/man-pages/man1/perf-intel-pt.1.html:

       To select snapshot mode a new option has been added:

           -S

       Optionally it can be followed by the snapshot size e.g.

           -S0x100000

       The default snapshot size is the auxtrace mmap size. If neither
       auxtrace mmap size nor snapshot size is specified, then the
       default is 4MiB for privileged users (or if
       /proc/sys/kernel/perf_event_paranoid < 0), 128KiB for
       unprivileged users. If an unprivileged user does not specify mmap
       pages, the mmap pages will be reduced as described in the new
       auxtrace mmap size option section below.

       The snapshot size is displayed if the option -vv is used e.g.

           Intel PT snapshot size: %zu

**Comment by cgaebel** [comment]
I looked into this a little and it's actually non-trivial. Sure, we've just got to pass an argument around, but that argument is actually some combination of snapshot-size and auxtrace mmap size and this requires some more domain knowledge than is likely appropriate for a new contributor.
