### ISSUE TITLE
Fail gracefully

### ISSUE THREAD

**Issue by cgaebel** [janestreet/magic-trace#38]
When magic-trace first starts up, it should detect conditions that we know will never work and bail out early with a good error message when they're hit. [This wiki page ](https://github.com/janestreet/magic-trace/wiki/Supported-platforms,-programming-languages,-and-runtimes) contains a list of constraints we know about. Let's automate as much as we can.

**Comment by Xyene** [comment]
Related: https://github.com/janestreet/magic-trace/issues/34
