### ISSUE TITLE
magic-trace gives [unknown] symbol for symbols containing spaces

### ISSUE THREAD

**Issue by StephanDollberg** [janestreet/magic-trace#6]
magic-trace gives [unknown] symbol in the perfetto profile for symbols containing whitespace.

This is a very common scenario for C++ template types. 

Perf handles those fine by itself.

The regex at https://github.com/janestreet/magic-trace/blob/master/src/perf_tool_backend.ml#L104 is failing. It should probably use proper parsing instead.

**Comment by Xyene** [comment]
Could you give https://github.com/janestreet/magic-trace/issues/6 a try?

It works for me on a toy program, but I don't have a big C++ codebase to run it against.

![p](https://user-images.githubusercontent.com/1403503/158468160-3613213f-b984-40a7-8412-c30c84d0d987.png)
