### ISSUE TITLE
Perf_tool_backend doesn't recognize "tr strt tr end" 

### ISSUE THREAD

**Issue by billduff** [janestreet/magic-trace#80]
This shows up for me in our Go demo. E.g. we fail to parse this perf line:

"2118573/2118573 770614.599007116:   tr strt tr end                      0 [unknown] =>           4591e1 [unknown]"

I included a commented-out test for this in my recent pull request to the line-parsing code, for convenience of whoever fixes this.

**Comment by cgaebel** [comment]
Both Tudor and I think it should probably be interpreted as a Jump. But it's hard to verify that with the Go example because it's broken for unrelated reasons, too.
