### ISSUE TITLE
CI .deb packages should be built on Ubuntu 18.04

### ISSUE THREAD

**Issue by Xyene** [janestreet/magic-trace#86]
Currently they target 20.04 and thus limit compatibility to that or newer, but we should be able to ~easily downgrade to 18.04 (the oldest release supported by GitHub actions).

**Comment by quantum5** [comment]
The difficulty of this has been vastly underestimated. For one, bionic doesn't have `dune` so the Debian build script won't work.

**Comment by Xyene** [comment]
Yeah, let's not do it.
